# -*- coding: utf-8 -*-
import scrapy
# from __future__ import division
from scrapy_splash import SplashRequest
import pdb
import urllib

class A99acressSpider(scrapy.Spider):
    name = '99acress'
    allowed_domains = ['99acres.com']
    
    def __init__(self, name=None, *args, **kwargs):
        self.start_url=[]
        self.result_url=[]
        self.localit=['Whitefield',
     'Sarjapur Road',
     'Electronic City Phase I',
     'Marathahalli',
     'HSR Layout',
     'Koramangala',
     'Bellandur',
     'Bannerghatta Road',
     'Mahadevapura',
     'JP Nagar',
     'BTM Layout',
     'BTM Layout',
     'Doddenakundi',
     'Kanakapura Road',
     'Indira Nagar',
     'K R Puram',
     'Brookefield',
     'Thanisandra Main Road',
     'Yelahanka',
     'Hennur',
     'Horamavu',
     'Ramamurthy Nagar',
     'Jayanagar',
     'Hosur Road',
     'Panathur',
     'Electronic City Phase II',
     'Hebbal',
     'Kundalahalli',
     'Marathahalli-Sarjapur Outer Ring Road',
     'Kaggadasapura',
     'CV Raman Nagar',
     'Banashankari',
     'Hosa Road',
     'Old Airport Road',
     'Old Madras Road',
     'Budigere',
     'Hoodi',
     'Off Sarjapur road',
     'Varthur',
     'Sarjapur',
     'Harlur',
     'Rajaji Nagar',
     'Bommanahalli',
     'Haralur Road',
     'Kadugodi',
     'HBR Layout',
     'Raja Rajeshwari Nagar',
     'Kasturi Nagar',
     'Yeshwanthpur',
     'Domlur',
     'Vijayanagar',
     'Kalyan Nagar',
     'Thubarahalli',
     'RT Nagar',
     'Banaswadi',
     'Begur Road',
     'Kasavanahalli',
     'Bilekahalli',
     'Malleshwaram',
     'Chandapura',
     'Yelahanka New Town',
     'Vidyaranyapura',
     'Thanisandra',
     'Hennur',
     'AECS Layout',
     'Devanahalli',
     'Ulsoor',
     'Chandapura Anekal Road',
     'Kadubeesanahalli',
     'Begur',
     'Marathahalli ORR',
     'Doddaballapur Road',
     'Jalahalli West',
     'Mysore Road',
     'Sahakara Nagar',
     'Jakkur',
     'Bellandur Outer Ring Road',
     'Basaveshwara Nagar',
     'Murugeshpalya',
     'Uttarahalli',
     'HSR Layout Sector 2',
     'Munnekollal',
     'JP Nagar Phase 8',
     'Basavanagudi',
     'JP Nagar Phase 7',
     'Tumkur Road',
     'Ejipura',
     'Nagarbhavi',
     'Singasandra',
     'Mathikere',
     'Kudlu Gate',
     'Hoskote',
     'Jigani',
     'Sarjapur Attibele Road',
     'kaikondrahalli',
     'Arekere',
     'HSR Layout Sector 1',
     'TC Palya Road',
     'Whitefield Road',
     'Shigehalli',
     'Sanjay Nagar',
     'ITPL Road',
     'Kammanahalli',
     'New Thippasandra',
     'HRBR Layout',
     'Kodigehalli',
     'Chansandra',
     'Kengeri',
     'Gunjur',
     'Nagavara',
     'Babusa Palya',
     'Hulimavu',
     'Tavarekere-BTM',
     'Wilson Garden',
     'Frazer Town',
     'HSR Layout Sector 3',
     'HSR Layout Sector 7',
     'JP Nagar Phase 5',
     'Outer Ring Road',
     'JP Nagar Phase 6',
     'Nelamangala',
     'Vishweshwaraiah Layout',
     'Richmond Town',
     'Bommasandra',
     'Banashankari 3rd Stage',
     'BEML Layout',
     'MS Palya',
     'Kodihalli',
     'Pai Layout',
     'Gottigere',
     'Cooke Town',
     'Kumaraswamy Layout',
     'Seegehalli',
     'GM Palya',
     'Devarachikkanahalli',
     'Malleshpalya',
     'Magadi Road',
     'Attibele',
     'Anjanapura',
     'Kalkere',
     'Kengeri Satellite Town',
     'Vignana Nagar',
     'Padmanabha Nagar',
     'RMV 2nd Stage',
     'Cox Town',
     'B Narayanapura',
     'Benson Town',
     'Akshayanagar',
     'Victoria Layout',
     'Kodichikkanahalli',
     'Basavanagar',
     'Dommasandra',
     'Varthur Road',
     'Lingarajapuram',
     'Mahalakshmi Layout',
     'Silk Board',
     'JP Nagar Phase 9',
     'Nagondanahalli',
     'Anekal',
     'Yemalur',
     'Hebbal Kempapura',
     'Kothanur',
     'JP Nagar Phase 1',
     'Bagaluru',
     'Shanthi Nagar',
     'Basapura',
     'Maruthi Sevanagar',
     'Doddakannalli',
     'HAL Layout',
     'JP Nagar Phase 2',
     'Horamavu Agara',
     'OMBR Layout',
     'Aavalahalli',
     'Bannerghatta',
     'Vasanth Nagar',
     'Battarahalli',
     'Kudlu',
     'Kathriguppe',
     'Thavarekere-Magadi Road',
     'Bhoganhalli',
     'Jeevanbheema Nagar',
     'Hanumantha Nagar',
     'Hegde Nagar',
     'Amrutha Halli',
     'MG Road',
     'Devanahalli Road',
     'IVC Road',
     'Margondanahalli',
     'Dasarahalli Hebbal',
     'Srinivasa Nagar',
     'Kaval Byrasandra',
     'Abbigere',
     'Kanaka Nagar',
     'Rachenahalli',
     'Adugodi',
     'Chandra Layout',
     'LB Shastri Nagar',
     'Chikka Banaswadi',
     'Bennigana Halli',
     'New BEL Road',
     'Belathur',
     'Girinagar',
     'Ganga Nagar',
     'Hoskote Malur Road',
     'Sarjapur Bagalur Road',
     'Kogilu',
     'Hongasandra',
     'International Airport Road',
     'Konanakunte',
     'Doddathoguru',
     'Wind Tunnel Road',
     'Panduranga Nagar',
     'Chinnapanna Halli',
     'Shivaji Nagar',
     'ISRO Layout',
     'Madiwala',
     'Siddapura',
     'Peenya',
     'Chamarajpet',
     'Sadashiva Nagar',
     'Nandini Layout',
     'Bellary Road',
     'Mico Layout',
     'Vijaya Bank Colony',
     'HSR Layout Sector 5',
     'Seshadripuram',
     'Ananth Nagar',
     'Richmond Road',
     'Garvebhavi Palya',
     'Immadihalli',
     'Srinagar',
     'Sompura',
     'Jakkasandra',
     'Chikkalasandra',
     'Jayamahal',
     'Dollars Colony',
     'Kempapura',
     'Dodda Banasvadi',
     'Nandi Hills',
     'Choodasandra',
     'Majestic',
     'Cambridge Layout',
     'Kammasandra',
     'Hesaraghatta',
     'Roopena Agrahara',
     'Rajanukunte',
     'Jakkuru Layout',
     'RMV Extension',
     'T Dasarahalli',
     'HSR Layout Sector 6',
     'JP Nagar Phase 4',
     'HAL Layout2',
     'Lavelle Road',
     'Maruthi Nagar',
     'Budigere Road',
     'Nagasandra',
     'Ramagondanahalli',
     'Chikbanavara',
     'Infantry Road',
     'Jalahalli Cross',
     'Byrathi',
     'Jagadish Nagar',
     'Hosakerehalli',
     'Subramanyapura',
     'Neeladri Nagar',
     'Sampangi Rama Nagar',
     'NRI Layout',
     'Rayasandra',
     'Laggere',
     'Srirampura',
     'Venkatapura',
     'R.K. Hegde Nagar',
     'Langford Town',
     'Viveka Nagar',
     'Uttarahalli Main Road',
     'Chelekare',
     'Neelasandra',
     'JP Nagar Phase 3',
     'HSR Layout Sector 4',
     'Jagajeevanram Nagar',
     'RMV',
     'BEML Layout Raja Rajeshwari Nagar',
     'Carmelaram',
     'Kartik Nagar',
     'Mallathahalli',
     'Hosapalaya',
     'Thippasandra',
     'Bagepalli',
     'Cunningham Road',
     'Doddabommasandra',
     'Ullal',
     'Dasarahalli Main Road',
     'Vinayaka Layout',
     'Vasanthapura',
     'Sudhama Nagar',
     'Richards Town',
     'Jalahalli East',
     'Kodathi',
     'Doddaballapur',
     'Gattahalli',
     'Balagere',
     'Kamaksipalya',
     'Chikka Tirupathi',
     'Doddakallasandra',
     'Commercial Street',
     'Bidadi',
     'Banashankari 5th Stage',
     'Kadugondanahalli',
     'Andrahalli',
     'Bagalakunte',
     'Chikkaballapur',
     'lal bagh',
     'Gauribidanur',
     'Nagarbhavi Circle',
     'Annapurneshwari Nagar',
     'Gandhi Nagar',
     'Ashok Nagar',
     'Soukya Road',
     'Vittal Mallya Road',
     'Yelachena Halli',
     'Bhuvaneshwari Nagar',
     'Kamanahalli',
     "Teacher's Colony",
     'St. Johns Road',
     'Cholanayakanahalli',
     'Nagadevanahalli',
     'Bidrahalli',
     'Bikasipura',
     'Jangamakote',
     'Sunkadakatte',
     'Chikkajala',
     'Devinagar',
     'Nayanda Halli',
     'Kalena Agrahara',
     'Malur-Hosur Road',
     'Kadabagere',
     'Guttahalli',
     'Attiguppe',
     'Bhoopasandra',
     'Bannerghatta Jigani Road',
     'Sadduguntepalya',
     'Huskur',
     'Thurahalli',
     'Nallurhalli',
     'HMT Layout',
     'Kacharakanahalli',
     'Bileshivale',
     'Maruthi Nagar (Yelahanka)',
     'Shettihalli',
     'Haragadde',
     'K Channasandra',
     'Kannamangala',
     'Byatarayanapura',
     'Talaghattapura',
     'Boyalahalli',
     'Hombegowda Nagar',
     'Rajiv Gandhi Nagar',
     'Kamala Nagar',
     'Doddakammanahalli',
     'Kempegowda Nagar',
     'Attibele - Anekal Road',
     'Kanakapura',
     'Gubalala',
     'Medihalli',
     'Kithiganur',
     'Brigade Road',
     'Jnana Ganga Nagar',
     'Chikkabellandur',
     'Koralur',
     'Kattigenahalli',
     'Dodda Aalada Mara Road',
     'Chikkabidarakallu',
     'Silver Springs Layout',
     'Kaggalipura',
     'Dooravani Nagar',
     'Palace Road',
     'Prashanth Nagar',
     'Nobo Nagar',
     'Kodigehalli - KR Puram',
     'SMV Layout',
     'Suryanagar',
     'Kumbalgodu',
     'Bommenahalli',
     'Munireddy Layout',
     'Chikkathoguru',
     'Baiyyappanahalli',
     'Virupakshapura',
     'Raghavendra Colony',
     'Shankarapura',
     'Jaya Chamarajendra Nagar',
     'Chinnapa Garden',
     'Garudachar Palya',
     'Wheeler Road',
     'Narasapura',
     'Ramohalli',
     'Harohalli',
     'Kolar Road',
     'Anagalapura',
     'Chokkanahalli',
     'Gunjur Mugalur Road',
     'Arasanakunte',
     'Bettahalasur',
     'Chikkakannalli',
     'Kallumantapa',
     'Kothanoor',
     'Sampigehalli',
     'Tilak Nagar',
     'Dayananda Nagar',
     'Bhovi Palya',
     'Chikka Tirupathi Road',
     'Soundarya Layout',
     'Vittal Nagar',
     'Ragavendra Nagar',
     'Sonnenahalli',
     'Chickpet',
     'Haudin Road',
     'Millers Road',
     'Yelanahalli',
     'Defence Colony - Bagalagunte',
     'Race Course Road',
     'Langford Road',
     'Chintamani',
     'Kuthaganahalli',
     'Tharabanahalli',
     'Shanthala Nagar',
     'Chikkagubbi',
     'Pattandur Agrahara',
     'Koppa',
     'Gollahalli',
     'Binny Pete',
     'Kodipur',
     'Lake City',
     'Munireddypalya',
     'Azad Nagar',
     'Rest House Road',
     "Richard's Park",
     'Cottonpete',
     'Dodsworth Layout',
     'Ashirvad Colony',
     'Doddabele',
     'Craig Park Layout',
     'Nelamangala - Chikkaballapura Road',
     'Vaderahalli',
     'Basavanna Nagar',
     'Huttanahalli',
     'Vijaypura',
     'Donnenahalli',
     'Chadalapura',
     'Meenakunte',
     'Lingadheeranahalli',
     'Residency Road',
     'Sidlaghatta',
     'Dabaspete',
     'Kalasipalayam',
     'Somashetti Halli',
     'Chikkanahalli',
     'Kolar-Chikkaballapur Road',
     'Singanahalli',
     'Karuna Nagar',
     'Belatur',
     'Chamundi Nagar',
     'Garden Layout',
     'Sankey Road',
     'Tippenahalli',
     'Bhaktharahalli',
     'Nehru Nagar',
     'Venkateshpuram',
     'Bapuji Nagar',
     'Williams Town',
     'Kammasandra Agrahara',
     'Bikkanahalli',
     'National Highway 207',
     'Kadusonnappanahalli',
     'Solur',
     'Chikkaballapur-Gauribidanur Road',
     'Doddenahalli',
     'Weavers Colony',
     'Hancharahalli',
     'Devasthanagalu',
     'Chikkabasavanapura',
     'Nanjappa Garden',
     'Budihal',
     'Seenappa Layout',
     'CQAL Layout',
     'Shanthi Pura',
     'Lakshmamma Layout',
     'Madhava Nagar',
     'Adakamaranahalli',
     'Vehloli',
     'Hullahalli',
     'Tharaballi',
     'Ganapathihalli',
     'Ballur',
     'Venkatagiri Kote',
     'Kunigal Road',
     'Essel Gardens',
     'S.Medihalli',
     'Koti Hosahalli',
     'Kommaghatta',
     'JP Nagar',
     'Kanakpura',
     'Outer Ring Road']
        for loc in self.localit:
        # url2='https://www.99acres.com/search/project/buy/residential/hebbal-bangalore?search_type=QS&search_location=CP20&lstAcn=CP_R&lstAcnId=20&src=CLUSTER&preference=S&selected_tab=3&city=20&res_com=R&isvoicesearch=N&keyword=sahakar %20nagar%20bangalore&np_search_type=R2M%2CNL%2CNP&strEntityMap=IiI%3D&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&searchform=1&price_min=null&price_max=null'
            url='https://www.99acres.com/search/project/buy/residential/'+urllib.quote(loc)+'?search_type=QS&search_location=CP20&lstAcn=CP_R&lstAcnId=20&src=CLUSTER&preference=S&selected_tab=3&city=21&res_com=R&isvoicesearch=N&keyword='+urllib.quote(loc)+'&strEntityMap=IiI%3D&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&searchform=1&price_min=null&price_max=null'
            self.start_url.append(url)
            # print(urllib.quote(url))
            # pdb.set_trace()
        super(A99acressSpider, self).__init__(*args, **kwargs)


    def start_requests(self):
        
        for url in self.start_url:
            yield SplashRequest(url, self.parsingurl,endpoint='render.json')

    def parsingurl(self,response):
        u_url=[]
        for i in response.css('div.pgdiv >a ::attr(href)').extract():
            u_url.append('https://www.99acres.com/'+i)
        # pdb.set_trace()
        for u in u_url:
            if len(u_url)-1:
                print u.replace("page-2", "page-1")
                u_url[len(u_url)-1]=u.replace("page-2", "page-1")
            # pdb.set_trace()
        for pas in u_url:
            yield scrapy.Request(pas, self.parseurl)
         

    def parseurl(self,response):
        item={}
        # pdb.set_trace()
        link_list=[]
        for x in response.css('div.npsrp_card'):
            link=''
            proj_name=''
            unit_type=x.css('tr.subHead >td._bedrm1::text').extract_first()
            status=x.css('tr.subHead >td._poss::text').extract_first()
            price_range=x.css('tr >td._price::text').extract_first()
            possession=x.css('tr >td._possl::text').extract_first()
            price_per_sqft=''
            for val in x.css('tr.subHead >td')[1].css('td.npsrp_tip::text').extract():
                price_per_sqft+=val


            for n in x.css('a.npt_titl_desc::text').extract():
                proj_name+=n
            for url in x.css('td.npsrp_head > a::attr(href)').extract():
                self.result_url.append(url)
                link+=url
                # yield SplashRequest(url, self.parse,endpoint='render.json')
            item={
            'link':link,
            'name':proj_name,
            'unit_type':unit_type,
            'status':status,
            'price_range':price_range,
            'possession':possession,
            'price_per_sqft':price_per_sqft,
            
            }
        
            link_list.append(item)
        for item_link in link_list:
            
            yield SplashRequest(item_link['link'], self.parse,meta={'items_val': item_link},args={'wait': 1.5})
    def parse(self, response):
        items = response.meta.get('items_val')
        proj_name=''
        links=''
        pro_detail=''
        about_project=''
        proj_plan=''
        about_builder=''
        
        val_dict={}
        for x in response.css('div.projFacts > div.secFactTable'):
            z= {}
            value=''
            key=x.css('span::text').extract()[0].strip()
            value=x.css('span::text').extract()[1]
           
            z={key:value}  
            val_dict.update(z) 
        about_project=response.css('div.prjctDesc ::text').extract()
        Project_specifications=response.css('div.dev_specification ::text').extract()
        about_builder=response.css('div.dev_descTxt::text').extract()
        
        
        value_dict={}
        key=0
        for x in response.css('div.tco_cards'):
            z= {}
            value=''
            key=key+1
            value=x.css('div.tco_cards::attr(content)').extract_first()
            z={key:value}  
            value_dict.update(z)
        data=response.css('div#amenitiesSection ::text').extract()
        item={
        'pro_detail':pro_detail,
        'about_project':about_project,
        'proj_plan':proj_plan,
        'about_builder':about_builder,
        'project_overview':val_dict,
        'Project_specifications':Project_specifications,
        'project_price':value_dict,
        'data':data,
        'RERA-ID':response.css('div.npReraText >span >a ::text').extract(),

        }
        print item
        items.update(item)
        
        yield items