# -*- coding: utf-8 -*-
import scrapy
import pdb
import itertools


class ProptigerDataSpider(scrapy.Spider):
    name = 'proptiger_data'
    allowed_domains = ['proptiger.com']
    #start_urls = ['http://proptiger.com/']


    def __init__(self, *args, **kwargs):
        self.start_url=[]
        self.item_list=[]
        self.item_list2=[]
        z_name=''
        self.localit=["Bennigana Halli",
        "Bidadi",
        "Bilekahalli",
        "Bommasandra",
        "Brookefield",
        "BTM Layout",
        "Carmelaram",
        "CV Raman Nagar",
        "Aavalahalli",
        "Budigere",
        "Doddenakundi",
        "Abbigere",
        "Adakamaranahalli",
        "AECS Layout",
        "Akshayanagar",
        "Bettahalasur",
        "Bhaktharahalli",
        "Bhoganhalli",
        "Bhoopasandra",
        "Bhovi Palya",
        "Bhuvaneshwari Nagar",
        "Bikasipura",
        "Bikkanahalli",
        "Bommenahalli",
        "Boyalahalli",
        "Brigade Road",
        "Budigere Road",
        "Budihal",
        "Ullal",
        "Venkatapura",
        "Venkateshpuram",
        "Vijaypura",
        "BEML Layout Raja Rajeshwari Nagar",
        "Bileshivale",
        "Binny Pete",
        "Chikkanagamangala",
        "Chikkanahalli",
        "Dasarahalli Main Road",
        "Hosakerehalli",
        "Kattigenahalli",
        "Kaval Byrasandra",
        "Kempegowda Nagar",
        "Kengeri Satellite Town",
        "Lingadheeranahalli",
        "Madhava Nagar",
        "Mahalakshmi Layout",
        "Majestic",
        "Marathahalli ORR",
        "Marathahalli-Sarjapur Outer Ring Road",
        "Ramohalli",
        "Richard's Park",
        "Richards Town",
        "Richmond Road",
        "Huskur",
        "JP Nagar",
        "Lake City",
        "Lakshmamma Layout",
        "Mysore Road",
        "Nagadevanahalli",
        "Nagarbhavi Circle",
        "Nagondanahalli",
        "Nallurhalli",
        "Nandi Hills",
        "Nandini Layout",
        "Nanjappa Garden",
        "Narasapura",
        "National Highway 207",
        "Neeladri Nagar",
        "Neelasandra",
        "Nehru Nagar",
        "Nelamangala - Chikkaballapura Road",
        "New BEL Road",
        "Bagepalli",
        "Adugodi",
        "Ashok Nagar",
        "Begur",
        "Richmond Town",
        "RMV",
        "Sadashiva Nagar",
        "Mahadevapura",
        "Panduranga Nagar",
        "Anagalapura",
        "Bagaluru",
        "Babusa Palya",
        "Bagalakunte",
        "Baiyyappanahalli",
        "Balagere",
        "Ballur",
        "Amrutha Halli",
        "Ananth Nagar",
        "Andrahalli",
        "Annapurneshwari Nagar",
        "Arasanakunte",
        "Arekere",
        "Ashirvad Colony",
        "Attibele - Anekal Road",
        "Attiguppe",
        "Azad Nagar",
        "Basaveshwara Nagar",
        "B Narayanapura",
        "Bangalore- Hyderabad Highway Road",
        "Bannerghatta Jigani Road",
        "Bapuji Nagar",
        "Basapura",
        "Basavanagar",
        "Basavanna Nagar",
        "Battarahalli",
        "Begur Road",
        "Belathur",
        "Belatur",
        "Bellary Road",
        "Nobo Nagar",
        "NRI Layout",
        "Off Sarjapur road",
        "Old Airport Road",
        "Old Madras Road",
        "OMBR Layout",
        "Palace Road",
        "Rajanukunte",
        "Kundalahalli",
        "Byrathi",
        "Cambridge Layout",
        "Devinagar",
        "Dodda Aalada Mara Road",
        "Dodda Banasvadi",
        "Doddaballapur Road",
        "Doddabommasandra",
        "Doddakammanahalli",
        "Doddathoguru",
        "Hosur Road",
        "Kodigehalli - KR Puram",
        "Lingarajapuram",
        "Peenya",
        "Raja Rajeshwari Nagar",
        "Magadi Road",
        "Sanjay Nagar",
        "Sarjapur",
        "Seshadripuram",
        "Shivaji Nagar",
        "Chamarajpet",
        "Chandapura",
        "Chintamani",
        "Vasanth Nagar",
        "Vidyaranyapura",
        "Chikkagubbi Village",
        "Bellandur Outer Ring Road",
        "BEML Layout",
        "Koti Hosahalli",
        "Kudlu Gate",
        "Kunigal Road",
        "Langford Town",
        "Lavelle Road",
        "LB Shastri Nagar",
        "RMV 2nd Stage",
        "Anjanapura",
        "Devanahalli",
        "Domlur",
        "Harohalli",
        "Hoodi",
        "Horamavu",
        "Marathahalli",
        "Padmanabha Nagar",
        "Rajaji Nagar",
        "Ramagondanahalli",
        "Ramamurthy Nagar",
        "Malur-Hosur Road",
        "Murugeshpalya",
        "Nagavara",
        "Narayanapura",
        "Nayanda Halli",
        "Nelamangala",
        "Cholanayakanahalli",
        "Choodasandra",
        "Commercial Street",
        "Cooke Town",
        "Cottonpete",
        "Doddagubbi",
        "Doddakallasandra",
        "Dommasandra",
        "Girinagar",
        "Gunjur",
        "Hebbal Kempapura",
        "Kathriguppe",
        "Singasandra",
        "Chickpet",
        "Subramanyapura",
        "Sudhama Nagar",
        "Sunkadakatte",
        "Talaghattapura",
        "Ulsoor",
        "Varthur",
        "Chikkaballapur",
        "Malleshwaram",
        "Siddapura",
        "Sidlaghatta",
        "Silk Board",
        "Silver Springs Layout",
        "Singanahalli",
        "Sompura",
        "Srinagar",
        "Srinivasa Nagar",
        "Tavarekere-BTM",
        "TC Palya Road",
        "Chikkabellandur",
        "Chikkajala",
        "Kurudusonnenahalli",
        "Kuthaganahalli",
        "Laggere",
        "Madiwala",
        "Malleshpalya",
        "Mayaghanahalli",
        "Medihalli",
        "Meenakunte",
        "MG Road",
        "Millers Road",
        "MS Palya",
        "Munireddy Layout",
        "Munireddypalya",
        "Munnekollal",
        "SMV Layout",
        "Solur",
        "Somashetti Halli",
        "Sonnenahalli",
        "Soukya Road",
        "Soundarya Layout",
        "Srirampura",
        "St. Johns Road",
        "Sulikere",
        "Suryanagar",
        "T Dasarahalli",
        "Tharabanahalli",
        "Thavarekere-Magadi Road",
        "Doddenahalli",
        "HMT Layout",
        "Horamavu Agara",
        "HSR Layout Sector 1",
        "Dabaspete",
        "Kadugodi",
        "Kanakapura",
        "Kannamangala",
        "Kodigehalli",
        "Kogilu",
        "Konanakunte",
        "Koramangala",
        "HSR Layout",
        "Kanakapura Road",
        "Kasavanahalli",
        "Kolar Road",
        "Vasanthapura",
        "Byatarayanapura",
        "Bylkonehalli",
        "Chadalapura",
        "Chamundi Nagar",
        "Cunningham Road",
        "Dayananda Nagar",
        "Defence Colony - Bagalagunte",
        "Devanahalli Road",
        "Devarachikkanahalli",
        "Devasthanagalu",
        "Doddabele",
        "Doddakannalli",
        "Dodsworth Layout",
        "Dollars Colony",
        "Donnenahalli",
        "Dooravani Nagar",
        "Ejipura",
        "Kalkunte",
        "Kamaksipalya",
        "Kamanahalli",
        "Kambalipura",
        "Kambipura",
        "Kammanahalli",
        "Kammasandra",
        "Kammasandra Agrahara",
        "Kanaka Nagar",
        "Kartik Nagar",
        "Karuna Nagar",
        "Kasturi Nagar",
        "Kithiganur",
        "Kodichikkanahalli",
        "Kolar-Chikkaballapur Road",
        "Kommaghatta",
        "Konena Agrahara",
        "Kothanoor",
        "Kempapura",
        "Kothanur",
        "Mallathahalli",
        "Kumbalgodu",
        "Doddaballapur",
        "Harlur",
        "Hoskote",
        "Indira Nagar",
        "Kalyan Nagar",
        "Kumaraswamy Layout",
        "Chikkalasandra",
        "Dasarahalli Hebbal",
        "Sahakara Nagar",
        "Sarjapur Attibele Road",
        "Sarjapur Bagalur Road",
        "Sarjapur Road",
        "Vijayanagar",
        "RMV Extension",
        "Sampigehalli",
        "Sankey Road",
        "Sathanur",
        "Seegehalli",
        "Seenappa Layout",
        "Shankarapura",
        "Shanthala Nagar",
        "Shanthi Nagar",
        "Shanthi Pura",
        "Shettihalli",
        "Shigehalli",
        "Chandapura Anekal Road",
        "Chandapura-Sarjapura Road",
        "Chandra Layout",
        "Chansandra",
        "Chelekare",
        "Chikbanavara",
        "Chikka Banaswadi",
        "Chikka Tirupathi",
        "Chikka Tirupathi Road",
        "Chikkaballapur-Gauribidanur Road",
        "Chikkabasavanapura",
        "Chikkabidarakallu",
        "Chikkakannalli",
        "Chikkasagarahalli",
        "Chikkathoguru",
        "Chinnapa Garden",
        "Chinnapanna Halli",
        "Chokkanahalli",
        "Cox Town",
        "CQAL Layout",
        "Craig Park Layout",
        "Thubarahalli",
        "Thurahalli",
        "Tilak Nagar",
        "Tippenahalli",
        "Attibele",
        "Banashankari",
        "Banashankari",
        "Banaswadi",
        "Bannerghatta",
        "Basavanagudi",
        "Bellandur",
        "Bommanahalli",
        "Nagarbhavi",
        "Anekal",
        "ITPL Road",
        "Maruthi Sevanagar",
        "Mathikere",
        "Outer Ring Road",
        "Pai Layout",
        "Pattandur Agrahara",
        "Pattegarhpalya",
        "Prashanth Nagar",
        "R.K. Hegde Nagar",
        "Race Course Road",
        "Rachenahalli",
        "Ragavendra Nagar",
        "Raghavendra Colony",
        "Raghuvanahalli",
        "Rajiv Gandhi Nagar",
        "Rayasandra",
        "Residency Road",
        "Rest House Road",
        "Banashankari 3rd Stage",
        "Banashankari 5th Stage",
        "Bannerghatta Road",
        "Benson Town",
        "Bidrahalli",
        "Hombegowda Nagar",
        "Hosapalaya",
        "Hoskote Malur Road",
        "HRBR Layout",
        "HSR Layout Sector 2",
        "HSR Layout Sector 3",
        "HSR Layout Sector 4",
        "HSR Layout Sector 5",
        "HSR Layout Sector 6",
        "HSR Layout Sector 7",
        "Hullahalli",
        "Huttanahalli",
        "Immadihalli",
        "Infantry Road",
        "International Airport Road",
        "ISRO Layout",
        "IVC Road",
        "Margondanahalli",
        "Maruthi Nagar",
        "Maruthi Nagar (Yelahanka)",
        "Masti - Malur Road",
        "JP Nagar Phase 8",
        "Hennur",
        "Hosa Road",
        "JP Nagar Phase 1",
        "JP Nagar Phase 2",
        "JP Nagar Phase 3",
        "JP Nagar Phase 4",
        "JP Nagar Phase 5",
        "JP Nagar Phase 6",
        "JP Nagar Phase 7",
        "JP Nagar Phase 9",
        "Kengeri",
        "Kudlu",
        "Thanisandra",
        "Jeevanbheema Nagar",
        "Kodihalli",
        "Thanisandra Main Road",
        "Mico Layout",
        "Nagasandra",
        "New Thippasandra",
        "Panathur",
        "Roopena Agrahara",
        "RT Nagar",
        "S.Medihalli",
        "Sadduguntepalya",
        "Sampangi Rama Nagar",
        "Hegde Nagar",
        "Jagadish Nagar",
        "Jagajeevanram Nagar",
        "Jakkasandra",
        "Jakkuru Layout",
        "Jangamakote",
        "Jaya Chamarajendra Nagar",
        "Jigani Anekal Road",
        "Jnana Ganga Nagar",
        "Judicial Layout",
        "K Channasandra",
        "K R Puram",
        "Kadubeesanahalli",
        "Kadugondanahalli",
        "Kadusonnappanahalli",
        "Kaggadasapura",
        "Kaggalipura",
        "kaikondrahalli",
        "Kalasipalayam",
        "Kalena Agrahara",
        "Kalkere",
        "Kallahalli",
        "Kallumantapa",
        "Frazer Town",
        "Gauribidanur",
        "Gottigere",
        "Hebbal",
        "Wilson Garden",
        "Yelahanka",
        "Hesaraghatta",
        "Hulimavu",
        "Jakkur",
        "Jayanagar",
        "Jigani",
        "Electronic City Phase I",
        "Electronic City Phase II",
        "Whitefield",
        "Yeshwanthpur",
        "Jalahalli Cross",
        "Hennur Road",
        "Kamala Nagar",
        "Kodathi",
        "Kodipur",
        "Koppa",
        "Koralur",
        "lal bagh",
        "Langford Road",
        "Teacher's Colony",
        "Tharaballi",
        "Essel Gardens",
        "Ganapathihalli",
        "Gandhi Nagar",
        "Ganga Nagar",
        "Garden Layout",
        "Garudachar Palya",
        "Garvebhavi Palya",
        "Gattahalli",
        "GM Palya",
        "Gollahalli",
        "Gubalala",
        "Guddahatti",
        "Gunjur Mugalur Road",
        "Guttahalli",
        "HAL Layout",
        "HAL Layout2",
        "Hancharahalli",
        "Hanumantha Nagar",
        "Haragadde",
        "Haralur Road",
        "Haudin Road",
        "HBR Layout",
        "Hemmigepura",
        "Kadabagere",
        "Vittal Nagar",
        "Whitefield Road",
        "Yelachena Halli",
        "Yelahanka New Town",
        "Yemalur",
        "Hongasandra",
        "Jalahalli East",
        "Jalahalli West",
        "Jayamahal",
        "Kacharakanahalli",
        "Thippasandra",
        "Tumkur Road",
        "Uttarahalli Main Road",
        "Vaderahalli",
        "Varthur Road",
        "Veerannapalya",
        "Vehloli",
        "Venkatagiri Kote",
        "Victoria Layout",
        "Vignana Nagar",
        "Vijaya Bank Colony",
        "Vinayaka Layout",
        "Virupakshapura",
        "Vishweshwaraiah Layout",
        "Vittal Mallya Road",
        "Viveka Nagar",
        "Weavers Colony",
        "Wheeler Road",
        "Williams Town",
        "Wind Tunnel Road",
        "Yarandahalli",
        "Yelanahalli",
        "Uttarahalli",
        "Uttarahalli"]
        
        self.prop_id=["52149",
        "51647",
        "51126",
        "51499",
        "50169",
        "50392",
        "52361",
        "50163",
        "52351",
        "53111",
        "51449",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "53126",
        "52720",
        "50157",
        "50185",
        "50160",
        "51510",
        "51455",
        "51453",
        "53152",
        "52696",
        "51545",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "51165",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "50187",
        "50167",
        "51092",
        "52710",
        "50271",
        "52713",
        "50179",
        "51641",
        "51512",
        "51513",
        "52335",
        "51152",
        "57247",
        "51638",
        "51625",
        "52695",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "51204",
        "50174",
        "51501",
        "51683",
        "63835",
        "50369",
        "50164",
        "51508",
        "51181",
        "51447",
        "51129",
        "51459",
        "51161",
        "50372",
        "51087",
        "62803",
        "50373",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "70645",
        "57210",
        "53143",
        "53325",
        "52801",
        "53156",
        "50159",
        "51998",
        "50347",
        "50181",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "50268",
        "51502",
        "52715",
        "63868",
        "51112",
        "52771",
        "53155",
        "50317",
        "50387",
        "52236",
        "91282",
        "52321",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "52333",
        "50173",
        "51635",
        "51143",
        "50162",
        "51503",
        "53142",
        "78126",
        "56697",
        "51077",
        "52297",
        "52296",
        "52298",
        "50339",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "51219",
        "50265",
        "50265",
        "51097",
        "50184",
        "50370",
        "50270",
        "51160",
        "51156",
        "50359",
        "51656",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "53153",
        "50176",
        "51451",
        "53146",
        "53147",
        "53148",
        "53149",
        "53150",
        "53151",
        "50188",
        "53154",
        "51078",
        "51113",
        "50180",
        "52306",
        "52718",
        "52697",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "50273",
        "53127",
        "51188",
        "50175",
        "51468",
        "50172",
        "51448",
        "52703",
        "50338",
        "50394",
        "50362",
        "50186",
        "68601",
        "50161",
        "50183",
        "50177",
        "52694",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "50204",
        "50204"]
        # term=self.name.split()
        for id,loc in itertools.izip_longest(self.prop_id,self.localit):
            print(id,loc)
            # term=loc
            # if len(term)>1:
            #     for i in range(0,len(term)):
                    
            #         if i!=(len(term)-1):
            #             z_name+=term[i]+'-'
            #         else:
            #             z_name+=term[i]
            # else:
            #     z_name=loc
           
            #for i in range(1,5):
                #if i==1:
                    #j=1
                #else:
                    #j=2
            url='https://www.proptiger.com/bangalore/property-sale-%s-%s?listingType=new'%(loc,id)
            self.start_url.append(url)
            
           
        
        super(ProptigerDataSpider, self).__init__(*args, **kwargs)


    def start_requests(self):
       
        for url in self.start_url:
            yield scrapy.Request(url, callback=self.parse_details, dont_filter=True)


    def parse_details(self,response):
        item={}
        
        link_list=[]
        for x in response.css('section.project-card-main-wrapper'):
            project_name=''
            link=''
            
            project_name=x.css('div.proj-name >a >span::text').extract_first()
            link=response.urljoin(x.css('div.proj-name >a::attr(href)').extract_first())
            location=x.css('div.loc >span::text').extract_first()
            project_by=x.css('div.projectBuilder >a  >span::text').extract_first()
            possesion_date=x.css('div.possession-wrap >span ::text').extract_first()
            rera_id=x.css('div.rera-id ::text').extract_first()
            item={'project_name':project_name,
                  'link':link,
                  'location':location,
                  'project_by':project_by,
                  'possesion_date':possesion_date,
                  'rera_id':rera_id
                  }
            
            link_list.append(item)

        item_list=response.css('div.stream-cont-info >ul >li >a::attr(href)').extract()
        for x in item_list:
            url=response.urljoin(x)
            yield scrapy.Request(url, callback=self.parse_details)
            
        if link_list:
            for item_link in link_list:
                yield scrapy.Request(item_link['link'],callback=self.fetch_detail,meta={'items_val': item_link}) 
                
                
                
    def fetch_detail(self,response):
        
        items = response.meta.get('items_val')
        
        final_dict={}
        
        for x in response.css('ul.overview-list >li'):
            key=''
            value=''
            z={}
            key_temp=''
            value=x.css('li.overview-item >div.overview-value ::text').extract_first()
            key=x.css('li.overview-item >div.overview-label::text').extract_first()
            if 'Total Launched' in key.strip():
                key_temp='total_unit'
            else:
                key_temp=key.strip()
            z={key_temp:value}
            final_dict.update(z)
        project_spec={}   
        for x in  response.css('div.project-spec-wrap div.project-spec'):
            value=''
            key=''
            for x1 in  x.css('div.project-spec > div.spec-value ::text').extract():
                value+=x1
            value=value.split('{')[0]   
            
            for x1 in x.css('div.project-spec > div.spec-label ::text').extract():
                key+=x1
                
            z={}
            z={key.strip():value}
            project_spec.update(z)
        project_desciption=''
        for x in response.css('div.project-desc-wrap >p.full-desc::text').extract():
             project_desciption+=x
             
        z=0
        amenities=''
        for x in response.css('section.amenities-wrap ul >li'):
            z+=1
            amenities+=' '+str(z)+': '+x.css('div.amenity-name::text').extract_first()+' '
        
        final_spec={}
        for x in response.css('section#specifications div.spec-block'):
            title=''
            
            spec_dict={}
            title=x.css('div.spec-title ::text').extract_first().strip()
            temp_dict={}
            for x1 in x.css('div.spec-row'):
                key=''
                val=''
                key=x1.css('div.spec-lbl::text').extract_first().strip()
                val=x1.css('div.spec-val::text').extract_first()
                z={}
                z={key:val}
                temp_dict.update(z)
            spec_dict={title:temp_dict}
            final_spec.update(spec_dict)
        
        final_list=[]
        unit_type=response.css('ul.config-range >li ::text').extract()
        if len(unit_type)==len(response.css('table.config-table')):
            
            for j in range(0,len(response.css('table.config-table'))):
                x=response.css('table.config-table')[j]
                header=[]
                col=[]
                if len(x.css('tr > th ::text').extract())>3:
                    header=x.css('tr > th ::text').extract()[:-1]
                else:
                    header=x.css('tr > th ::text').extract()
                hear_temp=[]    
                for values1 in header:
                    if 'Floor' in values1:
                        hear_temp.append('floor_plan')
                    if 'Area' in values1:
                        hear_temp.append('area')
                    if 'Price' in values1:
                        hear_temp.append('price')
                        
                        
                for x3 in x.css('tr')[1:]:
                    
                    semi_val=[]
                    for x1 in x3.css('td'):
                        value=''
                        for x2 in x1.css('td ::text').extract():
                            value+=x2
                        semi_val.append(value)  
                    col.append(semi_val)    
                
                
                for values in col:
                    dict_temp={}
                    #final_list1=[]
                    for i in range(0,len(hear_temp)):
                        
                        z={}
                        z={hear_temp[i].strip():values[i]}
                        dict_temp.update(z)
                        z={'unit_type':unit_type[j]}
                        dict_temp.update(z)
                    final_list.append(dict_temp) 
        else:
            for x in response.css('table.config-table'):
                header=[]
                col=[]
                if len(x.css('tr > th ::text').extract())>3:
                    header=x.css('tr > th ::text').extract()[:-1]
                else:
                    header=x.css('tr > th ::text').extract()
                hear_temp=[]    
                for values in header:
                    if 'Floor' in values:
                        hear_temp.append('floor_plan')
                    if 'Area' in values:
                        hear_temp.append('area')
                    if 'Price' in values:
                        hear_temp.append('price')
                        
                        
                for x3 in x.css('tr')[1:]:
                    
                    semi_val=[]
                    for x1 in x3.css('td'):
                        value=''
                        for x2 in x1.css('td ::text').extract():
                            value+=x2
                        semi_val.append(value)  
                    col.append(semi_val)    
                
                
                for values in col:
                    dict_temp={}
                    #final_list1=[]
                    for i in range(0,len(hear_temp)):
                        
                        z={}
                        z={hear_temp[i].strip():values[i]}
                        dict_temp.update(z)
                        z={'unit_type':'NA'}
                        dict_temp.update(z)
                    final_list.append(dict_temp) 
        builder_overview=''
        for x in response.css('ul.three-points > li'):
            builder_overview+=' ('+(x.css('span.number::text').extract_first() if x.css('span.number::text').extract_first() else '')+'  '+(x.css('span.desc::text').extract_first() if x.css('span.desc::text').extract_first() else '')+' )'
            
        builder_desciption=''
        for x in response.css('div.builder-desc ::text').extract():
            builder_desciption+=x
            
        item={'project_overview':final_dict,
              'status':final_dict['Status'],
              'total_unit':final_dict['total_unit'],
              'project_spec':project_spec,
              'Apartment':project_spec['Apartment'],
              'Super_builduparea':project_spec['Super Builtup area1 sq M = 10.76 sq ft'],
              'Builder_price':project_spec['Builder price'],
              'project_desciption':project_desciption,
              'amenities':amenities,
              'project_add_spec':final_spec,
              # 'table_inventory':final_list,
              'unit_type':dict_temp['unit_type'],
              'area':dict_temp['area'],
              'builder_overview':builder_overview,
              'builder_desciption':builder_desciption}    
        items.update(item)
        
        yield items
            
        
          
